/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment1;

/**
 *
 * @author n01007309
 */
public class TestBoard extends javax.swing.JFrame {

    /**
     * Creates new form TestBoard
     */
    public TestBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChessTile00 = new javax.swing.JButton();
        ChessTile01 = new javax.swing.JButton();
        ChessTile02 = new javax.swing.JButton();
        ChessTile03 = new javax.swing.JButton();
        ChessTile04 = new javax.swing.JButton();
        ChessTile05 = new javax.swing.JButton();
        ChessTile06 = new javax.swing.JButton();
        ChessTile07 = new javax.swing.JButton();
        ChessTile10 = new javax.swing.JButton();
        ChessTile11 = new javax.swing.JButton();
        ChessTile21 = new javax.swing.JButton();
        ChessTile31 = new javax.swing.JButton();
        ChessTile41 = new javax.swing.JButton();
        ChessTile51 = new javax.swing.JButton();
        ChessTile61 = new javax.swing.JButton();
        ChessTile71 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ChessTile00.setText("0");

        ChessTile01.setText("1");
        ChessTile01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChessTile01ActionPerformed(evt);
            }
        });

        ChessTile02.setText("jButton1");
        ChessTile02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChessTile02ActionPerformed(evt);
            }
        });

        ChessTile03.setText("jButton2");

        ChessTile04.setText("jButton3");
        ChessTile04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChessTile04ActionPerformed(evt);
            }
        });

        ChessTile05.setText("jButton4");

        ChessTile06.setText("jButton5");

        ChessTile07.setText("jButton6");

        ChessTile10.setText("jButton7");

        ChessTile11.setText("jButton8");

        ChessTile21.setText("jButton9");

        ChessTile31.setText("jButton10");

        ChessTile41.setText("jButton11");

        ChessTile51.setText("jButton12");

        ChessTile61.setText("jButton13");

        ChessTile71.setText("jButton14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChessTile10, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(ChessTile00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChessTile01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChessTile11, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChessTile02, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChessTile21, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChessTile03, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChessTile31, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChessTile04, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChessTile41, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChessTile05, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChessTile51, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChessTile06, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChessTile61, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChessTile07, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChessTile71, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChessTile10)
                    .addComponent(ChessTile11)
                    .addComponent(ChessTile21)
                    .addComponent(ChessTile31)
                    .addComponent(ChessTile41)
                    .addComponent(ChessTile51)
                    .addComponent(ChessTile61)
                    .addComponent(ChessTile71))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChessTile00)
                    .addComponent(ChessTile01)
                    .addComponent(ChessTile02)
                    .addComponent(ChessTile03)
                    .addComponent(ChessTile04)
                    .addComponent(ChessTile05)
                    .addComponent(ChessTile06)
                    .addComponent(ChessTile07))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChessTile04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChessTile04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChessTile04ActionPerformed

    private void ChessTile02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChessTile02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChessTile02ActionPerformed

    private void ChessTile01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChessTile01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChessTile01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChessTile00;
    private javax.swing.JButton ChessTile01;
    private javax.swing.JButton ChessTile02;
    private javax.swing.JButton ChessTile03;
    private javax.swing.JButton ChessTile04;
    private javax.swing.JButton ChessTile05;
    private javax.swing.JButton ChessTile06;
    private javax.swing.JButton ChessTile07;
    private javax.swing.JButton ChessTile10;
    private javax.swing.JButton ChessTile11;
    private javax.swing.JButton ChessTile21;
    private javax.swing.JButton ChessTile31;
    private javax.swing.JButton ChessTile41;
    private javax.swing.JButton ChessTile51;
    private javax.swing.JButton ChessTile61;
    private javax.swing.JButton ChessTile71;
    // End of variables declaration//GEN-END:variables
}
